# __Introduction to Tensors__

Tensors are fundamental data structures in deep learning and are similar to multi-dimensional arrays. They are a generalization of vectors and matrices to higher dimensions and provide a way to represent and manipulate numerical data efficiently.

Tensors can be seen as containers for numerical data that can be organized into a specific shape or size.

Let's understand how it works.

- In short Tensors are Multidimension arrays that are use to store data, perform mathematical operations , calculate derivatives 

# Step 1 : Import necessary libraries

In [1]:
# Disable oneDNN optimizations to avoid potential minor numerical differences caused by floating-point round-off errors.
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

In [2]:
# Set CUDA_VISIBLE_DEVICES:
#   "-1" -> force CPU-only execution
#   "0"  -> use first GPU (change to "1", "2", etc. for other GPUs)
os.environ['CUDA_VISIBLE_DEVICES'] = "-1"

In [3]:
# Suppresses TensorFlow's C++ backend logs. Levels:

# 0 = all logs (default, verbose — INFO, WARNING, ERROR)
# 1 = filter INFO
# 2 = filter INFO + WARNING
# 3 = filter INFO + WARNING + ERROR (only fatal messages show)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = "3"

In [4]:
# IMPORT LIBRARIES

import numpy as np
import tensorflow as tf

# Step2 - Rank 0 Tensor

- The rank is also know as order,degree or ndims

In [5]:
# create rank 0 tensor (i.e : Scalar)

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


# Step3 - Rank 1 Tensor


In [ ]:
rank_1_tensor = tf.constant([2.0,4.0,5.0])  # output = Tensor object with shape as 3 cols & dtype=float
print(rank_1_tensor)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)


In [7]:
rank_1_tensor = tf.constant([2,4,5])  # output = Tensor object with shape as 3 cols & dtype=int
print(rank_1_tensor)

tf.Tensor([2 4 5], shape=(3,), dtype=int32)


# Step4 - Rank 2 Tensor

- Rank2 which is 2d array, using tf.constant function

In [ ]:
rank_2_tensor = tf.constant([[1,2],
                             [3,4],
                             [5,6]], dtype= tf.float16)
print(rank_2_tensor)  

# int values passed with dtype as float

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


# Why are we building these Rank Tensors?

- Tensorflow is workflow, Tensor is a DataStructure
- The rank are building blocks of tensor -- how we create a vector, matrix - a foundation to create a manual tensor


# Step4 - Rank 3 Tensor

- Rank 3 tensor with shape of (3,2,5) , indicating 3 layers, each containing 2 rows and 5 cols

In [12]:
# (3,2,5)

rank_3_tensor = tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9]],

    [[10,11,12,13,14],
     [15,16,17,18,19]],

    [[20,21,22,23,24],
     [25,26,27,28,29]]
])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


# Step 6: Convert a Tensor to a NumPy array

In [13]:
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [14]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

# Step 7: Performing basic math on Tensors

- decalre variable a & b
- addition
- multiplication
- matrix multiplication

In [ ]:
# decalre 2x2  tensors a & b

a = tf.constant([[2,3],
                 [4,5]], dtype=tf.float32)

b = tf.constant([[1,1],
                 [1,1]], dtype=tf.float32)

# Element wise addition
print(tf.add(a,b), "\n")

# Element wise multiplication
print(tf.multiply(a,b), "\n")

# Matrix multiplication
print(tf.matmul(a,b), "\n")

tf.Tensor(
[[3. 4.]
 [5. 6.]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[5. 5.]
 [9. 9.]], shape=(2, 2), dtype=float32) 



# Step 8: Initalize the Tensor

- Max value in tensor
- Index of the max value in tensor
- Apply a  sfotmax activation function to a tensor to compute the probability distribution over all elements in the tensor

In [17]:
c = tf.constant([[4,5],
                 [10,1]], dtype=tf.float32)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  5.],
       [10.,  1.]], dtype=float32)>

In [18]:
# max value in tensor c

print(tf.reduce_max(c))

tf.Tensor(10.0, shape=(), dtype=float32)


In [ ]:
# index value of max value in the tensor c
# axis=0 , axis=cols --- by default axis=0 (rows)
print(tf.argmax(c))      

#    c1   c2
# R0 [4,  5]
# R1 [10, 1]
                                                                #C1       C2
# this copmares by rows, and checks in which row val is high [1(row1), 0(row0)]

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [ ]:
# Apply softmax activation to tensor c

print(tf.nn.softmax(c))   # tf.nn.softmax converts each row into a probability distribution

# Formula: for a row [x1, x2]:

# softmax(xi) = exp(xi) / (exp(x1) + exp(x2))

# Row 1: [4, 5]

# exp(4) = 54.598
# exp(5) = 148.413
# sum    = 203.011

# softmax = [54.598/203.011, 148.413/203.011] = [0.2689, 0.7311]

tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


# Step 9: Broadcast X & Y variables

- Reshape

In [ ]:
x = tf.constant([1,2,3,4,5,6])

# correct braodcasting
tf.reshape(x,(2,3))

# rows*cols should match total num of elements

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# can reshape tensors

# Different types of Tensors

- Ragged Tensor
- Scaler String tensor

In [ ]:
ragged_list = [
    [0,1,2,3,4],
    [5,6,7],
    [8,9],
    [10]
]

type(ragged_list)

# if python list passed to Tensorflow - > it will be converted to tensor

list

In [27]:
# convert list to ragged tensor

ragged_tensor = tf.ragged.constant(ragged_list)
type(ragged_tensor)

tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor

- Scaler string Tensor: it is a datatype, which means data can be represented as a string (variable lenght bytes arrays) in tensors

In [28]:
# create a scaler string tensor

scaler_string_tensor = tf.constant("gray wolf")

print(scaler_string_tensor)

tf.Tensor(b'gray wolf', shape=(), dtype=string)


## Wrap up 

- Tensor
- Numpy Array
- Rank 0 Tensor (Scalar)
- Rank 1 Tensor (Vector)
- Rank 2 Tensor (MaTrix) 
- Rank 3 Tensor (3D Matrix or Tensor)
- Arithmetic operations on tensors
- Initialising, Max value, Index of max value in axis =0, applying an activation function to a tensor
- Broadcasting (stretching the smaller tensor size to match the larger tensor if required)
- Reshaping and limitations of reshaping
- Ragged Tensors and Scalar String Tensors