# Numpy practice

In [27]:
import numpy as np

In [31]:
# Generate the synthetic dataset: 10-row arrays for price, quantity, discount, rating, days_to_deliver, category, and is_returned using np.random.

np.random.seed(42)

price = np.random.uniform(1, 100, 10).round(2)
quantity = np.random.randint(1, 20, 10)
discount = np.random.uniform(0.0, 0.50, 10).round(2)
rating = np.random.uniform(1, 5, 10).round(2)
days_to_deliver = np.random.randint(1, 10, 10)
category = np.random.randint(0, 5, 10)
is_returned = np.random.randint(0, 2, 10)

#  np.random.uniform = float
# np.random.randint = int

In [32]:
print("Price",price)
print("quantity",quantity)
print("discount",discount)
print("ratings",rating)
print("Days to deliver",days_to_deliver)
print("category",category)
print("Is returned",is_returned)

Price [38.08 95.12 73.47 60.27 16.45 16.44  6.75 86.75 60.51 71.1 ]
quantity [ 2 12  6  2  1 12 12 17 10 16]
discount [0.12 0.05 0.31 0.19 0.49 0.23 0.43 0.34 0.23 0.01]
ratings [4.77 3.25 2.54 1.06 1.92 1.96 3.73 3.44 4.33 1.69]
Days to deliver [1 4 2 8 4 2 6 6 4 6]
category [4 1 1 3 1 1 3 3 0 4]
Is returned [1 0 1 0 0 1 1 0 1 1]


In [33]:
# Create an array of 1000 order IDs starting from 1001

Order_ID = np.arange(1,11)
Order_ID

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# Create a revenue column by multiplying price × quantity × (1 - discount) entirely in NumPy — no loops.

revenue = price * quantity * (1-discount)

# check if the maths matches
print(price[0], quantity[0], discount[0])
print(price[0] * quantity[0] * (1-discount[0]))
print(revenue[0])

38.08 2 0.12
67.0208
67.0208


In [37]:
# Stack arrays joins different arrays with the axis, when axis=0 it creates rows, when axis=1 it creates columns
# by default axis=0-creates rows

# Stacking array is used to combine mulitple datasets into single structured array, allowing to perform vectorized operations, batch processing

stack_array = np.stack((price,quantity,discount,rating,days_to_deliver,category,is_returned))
stack_array

array([[3.808e+01, 9.512e+01, 7.347e+01, 6.027e+01, 1.645e+01, 1.644e+01,
        6.750e+00, 8.675e+01, 6.051e+01, 7.110e+01],
       [2.000e+00, 1.200e+01, 6.000e+00, 2.000e+00, 1.000e+00, 1.200e+01,
        1.200e+01, 1.700e+01, 1.000e+01, 1.600e+01],
       [1.200e-01, 5.000e-02, 3.100e-01, 1.900e-01, 4.900e-01, 2.300e-01,
        4.300e-01, 3.400e-01, 2.300e-01, 1.000e-02],
       [4.770e+00, 3.250e+00, 2.540e+00, 1.060e+00, 1.920e+00, 1.960e+00,
        3.730e+00, 3.440e+00, 4.330e+00, 1.690e+00],
       [1.000e+00, 4.000e+00, 2.000e+00, 8.000e+00, 4.000e+00, 2.000e+00,
        6.000e+00, 6.000e+00, 4.000e+00, 6.000e+00],
       [4.000e+00, 1.000e+00, 1.000e+00, 3.000e+00, 1.000e+00, 1.000e+00,
        3.000e+00, 3.000e+00, 0.000e+00, 4.000e+00],
       [1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        1.000e+00, 0.000e+00, 1.000e+00, 1.000e+00]])

In [38]:
# Create a copy of the price array and a view of it. 
# Modify the copy and verify the original is unchanged. 


copy_of_price = price.copy()
print("Copy array of price",copy_of_price)

copy_of_price[1] = 10   # modifying copy
print("1st index of original price array",price[1])
print("Copy after modifying",copy_of_price)

# Modifying the original does not change the copy
# Modifying the copy does not change the original

Copy array of price [38.08 95.12 73.47 60.27 16.45 16.44  6.75 86.75 60.51 71.1 ]
1st index of original price array 95.12
Copy after modifying [38.08 10.   73.47 60.27 16.45 16.44  6.75 86.75 60.51 71.1 ]


In [40]:
# View in array
## Then modify the view and verify the original changes.

print("Og array Price", price)

v1 = price.view()

# modify the view
v1[1] = 100

print("After modifying view", price)

# Modifying the view changes the original array

Og array Price [38.08 95.12 73.47 60.27 16.45 16.44  6.75 86.75 60.51 71.1 ]
After modifying view [ 38.08 100.    73.47  60.27  16.45  16.44   6.75  86.75  60.51  71.1 ]


# Slicing and Indexing

In [41]:
# Array Slicing
# Extract every 3rd order starting from index 0. What are their prices?

price[0::3]

array([38.08, 60.27,  6.75, 71.1 ])

In [42]:
# Extract the last 2 orders using negative indexing.
price[-2:]

array([60.51, 71.1 ])

In [43]:
# Use fancy indexing to retrieve prices at positions [0, 3, 6, 9]

positions = [0,3,6,9]
retrieve_price = price[positions]

print("Og array",price)
print("Retrieve price",retrieve_price)

Og array [ 38.08 100.    73.47  60.27  16.45  16.44   6.75  86.75  60.51  71.1 ]
Retrieve price [38.08 60.27  6.75 71.1 ]


In [44]:

stack_array

array([[3.808e+01, 9.512e+01, 7.347e+01, 6.027e+01, 1.645e+01, 1.644e+01,
        6.750e+00, 8.675e+01, 6.051e+01, 7.110e+01],
       [2.000e+00, 1.200e+01, 6.000e+00, 2.000e+00, 1.000e+00, 1.200e+01,
        1.200e+01, 1.700e+01, 1.000e+01, 1.600e+01],
       [1.200e-01, 5.000e-02, 3.100e-01, 1.900e-01, 4.900e-01, 2.300e-01,
        4.300e-01, 3.400e-01, 2.300e-01, 1.000e-02],
       [4.770e+00, 3.250e+00, 2.540e+00, 1.060e+00, 1.920e+00, 1.960e+00,
        3.730e+00, 3.440e+00, 4.330e+00, 1.690e+00],
       [1.000e+00, 4.000e+00, 2.000e+00, 8.000e+00, 4.000e+00, 2.000e+00,
        6.000e+00, 6.000e+00, 4.000e+00, 6.000e+00],
       [4.000e+00, 1.000e+00, 1.000e+00, 3.000e+00, 1.000e+00, 1.000e+00,
        3.000e+00, 3.000e+00, 0.000e+00, 4.000e+00],
       [1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        1.000e+00, 0.000e+00, 1.000e+00, 1.000e+00]])

In [45]:
# From the 2D stacked array, extract rows 1–5 and only the first 3 columns.
stack_array[1:5, :3] 

# syntax: arr(rows, cols) // mentioned how many rows, and columns 

array([[ 2.  , 12.  ,  6.  ],
       [ 0.12,  0.05,  0.31],
       [ 4.77,  3.25,  2.54],
       [ 1.  ,  4.  ,  2.  ]])

In [49]:
# Retrieve all orders where category equals 3 using index arrays returned by np.where.

category_3 = np.where(category==3)
print("Category",category)
print("Category 3 is on the order id",Order_ID[category_3])

Category [4 1 1 3 1 1 3 3 0 4]
Category 3 is on the order id [4 7 8]


In [47]:
Order_ID

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
category

array([4, 1, 1, 3, 1, 1, 3, 3, 0, 4], dtype=int32)

# Math

In [50]:
# Compute total revenue (price × quantity × (1 – discount)). Then find min, max, mean, and sum of revenue.
revenue

array([  67.0208, 1084.368 ,  304.1658,   97.6374,    8.3895,  151.9056,
         46.17  ,  973.335 ,  465.927 , 1126.224 ])

In [51]:
min_revenue = np.min(revenue)
max_revenue = np.max(revenue)

print("Max Revenue: ",max_revenue)
print("Min revenue: ",min_revenue)
print("Total of revenue:", np.sum(revenue))
print("Mean of revenue", np.mean(revenue))

Max Revenue:  1126.224
Min revenue:  8.3895
Total of revenue: 4325.1431
Mean of revenue 432.51431


In [52]:
# Compute the cumulative revenue over all 10 orders in order

print("Cumulative of revenue",np.cumsum(revenue))

# cumsum will calculate sum of previous numbers
# eg: arr(1,2,3,4)
# op:  [1, 3, 6, 10]  -> (1, 1+2, 1+2+3, 1+2+3+4)

# why cumsum is used - instead of long loops in python, cumsum shows the output at each step(iteration), which shows the progress of metrics at each step

Cumulative of revenue [  67.0208 1151.3888 1455.5546 1553.192  1561.5815 1713.4871 1759.6571
 2732.9921 3198.9191 4325.1431]


In [53]:
# For each category (0–5), compute the average price without using pandas or loops — only NumPy.
# calculate mean of each category

unique_category, inverse_indices = np.unique(category, return_inverse=True)

# sum up value for each category using bincount
group_categories = np.bincount(inverse_indices, weights = price)
group_count = np.bincount(inverse_indices)
group_mean = group_categories / group_count

print("Category wise mean")
print(dict(zip(unique_category,group_mean)))

# inverse_indices stores which locker does each category belongs to
# eg: unique_categor = [1,3,4]  [0,1,2]
# # inverse - from category array, [3,1,1,3] .. invers has [1,0,0,1]


Category wise mean
{np.int32(0): np.float64(60.51), np.int32(1): np.float64(51.589999999999996), np.int32(3): np.float64(51.25666666666667), np.int32(4): np.float64(54.589999999999996)}


In [ ]:
# Apply a 15% surcharge to all orders where days_to_deliver > 5. Update prices in place.

print("Prices before apply 15\'%' charge",price)
print("Days to Deliver",days_to_deliver)



Prices before apply 15'%' charge [ 38.08 100.    73.47  60.27  16.45  16.44   6.75  86.75  60.51  71.1 ]
Days to Deliver [1 4 2 8 4 2 6 6 4 6]


In [55]:
price = np.where(days_to_deliver>5, price*(1+0.15), price)

print("Prices after 15\'%' charge",price.round(2))

Prices after 15'%' charge [ 38.08 100.    73.47  69.31  16.45  16.44   7.76  99.76  60.51  81.76]


In [56]:
# Compute the product of all discount factors (1 - discount) for the first 3 orders.

compute_discount = np.prod(1-discount[:3])
compute_discount


np.float64(0.5768399999999999)

# Masking

In [ ]:
# Find all orders with a rating ≥ 4 AND price > 60. How many are there?

orders = np.where((rating>=4) & (price>=60))
print(Order_ID[orders])
print(rating[orders])
print(price[orders])

print(len(orders))

[9]
[4.33]
[60.51]
1


In [72]:
# Find orders that were either returned OR had a discount > 0.3. List their order indices.
print("Is returned",is_returned)
print("Discount", discount)

condition = np.where((discount >= 0.3) | (is_returned==1))

print("Orders which match this codintion are")

print(Order_ID[condition])

Is returned [1 0 1 0 0 1 1 0 1 1]
Discount [0.12 0.05 0.31 0.19 0.49 0.23 0.43 0.34 0.23 0.01]
Orders which match this codintion are
[ 1  3  5  6  7  8  9 10]


In [ ]:
# Replace all prices below the 10th percentile with the 10th percentile value (clip the bottom).
print("Price",price)

percentile_10 = np.percentile(price, 10)

print("Prices below 10th perecentile", percentile_10)

# The 10th percentile value is 15.57.
# That means 90% of prices are above 15.57 and 10% are below.

Price [ 38.08   100.      73.47    69.3105  16.45    16.44     7.7625  99.7625
  60.51    81.765 ]
Prices below 10th perecentile 15.57225


In [74]:
# Clip the bottom 10% prices with percentile value
print("Prices before the clip", price)

price= np.where(price < percentile_10, percentile_10, price)

print("Prices after the clip", price)

Prices before the clip [ 38.08   100.      73.47    69.3105  16.45    16.44     7.7625  99.7625
  60.51    81.765 ]
Prices after the clip [ 38.08    100.       73.47     69.3105   16.45     16.44     15.57225
  99.7625   60.51     81.765  ]


In [ ]:
# Count how many orders fall into each rating bucket (1, 2, 3, 4, 5) using only NumPy.
# bincount function needs "int" type values

rating = rating.astype(int)
print("Rating",rating)

print("How many orders each fall under each ratings",np.bincount(rating))


Rating [4 3 2 1 1 1 3 3 4 1]
How many orders each fall under each ratings [0 4 1 3 2]


In [95]:
# Find orders where price is an outlier — more than 2 standard deviations from the mean.
mean = np.mean(price)
std = np.std(price)

print("Mean price",mean)
print("STD", std)

# Get Outliers
lower = mean - (2*std)
higher = mean + (2*std)

prices =price[(price<lower) | (price>higher)]

print("Lower bound",lower)
print("higher bound",higher)
print("Outliers",len(prices))
#Mean > Std generally means that your average value is larger than the spread (variation) of data. 
# Which means data is relatively consistent rather than chaotic.

Mean price 57.136025
STD 31.76400790762439
Lower bound -6.391990815248782
higher bound 120.66404081524877
Outliers 0


# Sorting

In [99]:
# Sort all orders by price in ascending order. Return the sorted prices and their original indices.

print("Prices before sorting",price)
print()

sort_order_prices = np.sort(price)
print("Prices in Sorted order",sort_order_prices)

print()
sort_by_indices = np.argsort(price)
print("Indices of sorted order prices",sort_by_indices)

Prices before sorting [ 38.08    100.       73.47     69.3105   16.45     16.44     15.57225
  99.7625   60.51     81.765  ]

Prices in Sorted order [ 15.57225  16.44     16.45     38.08     60.51     69.3105   73.47
  81.765    99.7625  100.     ]

Indices of sorted order prices [6 5 4 0 8 3 2 9 7 1]


In [ ]:
# Find the top 3 most expensive orders using partition — not full sort.

# first partion the array, then return top 3

print("Prices before Partition sorting",price)
partition = np.partition(price,-3)[-3:]
print(partition)

# this codes starts partition from negative side, where it sorts the -3 in palce and all ele left to it are less and right to it are greater

# arr.partition returns the value 
# argpartition returns the indices at which it should be sorted

Prices before Partition sorting [ 38.08    100.       73.47     69.3105   16.45     16.44     15.57225
  99.7625   60.51     81.765  ]
[ 81.765   99.7625 100.    ]


In [110]:
# Find the index of the order with the minimum days_to_deliver.

print("Deliver days", days_to_deliver)
minimum_days = np.argmin(days_to_deliver)
max_days = np.argmax(days_to_deliver)

print("Minimun day is at index:",minimum_days)
print("Maximum day is at index:",max_days)

Deliver days [1 4 2 8 4 2 6 6 4 6]
Minimun day is at index: 0
Maximum day is at index: 3


In [126]:
# Check whether any order has a negative price and whether all ratings are between 1 and 5.

price_check = np.where(price<0)
print("Prices below 0:",(len(price_check[0])))

# check for rating 

is_between = ((rating<=5) & (rating>0)).all()
print(is_between)

Prices below 0: 0
True


In [138]:
# Find all unique category values and count how many orders each has.

print("Category",category)
unique_category = np.unique(category)
print("Unqiue Category",unique_category)

counts =  np.bincount(category)
print("Count of Orders under unique category")
print()
dict = ((zip(unique_category, counts[unique_category])))

for k, v in dict:
    print(k,v)

# there's no category for 2, hence 0 orders are under 2 category


Category [4 1 1 3 1 1 3 3 0 4]
Unqiue Category [0 1 3 4]
Count of Orders under unique category

0 1
1 4
3 3
4 2


# Shape - Reshape

In [ ]:
# Reshape the revenue array (10,) into shape (2,5). Then transpose it.

print("Reshape array")
revenue_reshape = (revenue.reshape(2,5))
print(revenue_reshape)

print()

print("Transpose array")
print(np.transpose(revenue_reshape))

# in transpose: Rows->columns, columns->rows

Reshape array
[[  67.0208 1084.368   304.1658   97.6374    8.3895]
 [ 151.9056   46.17    973.335   465.927  1126.224 ]]

Transpose array
[[  67.0208  151.9056]
 [1084.368    46.17  ]
 [ 304.1658  973.335 ]
 [  97.6374  465.927 ]
 [   8.3895 1126.224 ]]


In [151]:
# Flatten using flat and ravel
flat = revenue_reshape.flatten()

print("Flat array", flat)  

ravel = revenue_reshape.ravel()
print("Ravel array", ravel)

# Ravel - if modified changes the original array
# flatten - does affect the original array


Flat array [  67.0208  100.      304.1658   97.6374    8.3895  151.9056   46.17
  973.335   465.927  1126.224 ]
Ravel array [  67.0208  100.      304.1658   97.6374    8.3895  151.9056   46.17
  973.335   465.927  1126.224 ]


In [ ]:
# Add a new axis to the price array so it becomes (10, 1). Then broadcast-multiply it with a (1, 5) array of tax rates.

# make price of 1-d array (10,) to (10,1) - 10 rows , 1 col
print("Prices before",price)
new_price = price[:, np.newaxis]

tax_rates = np.array([0.05, 0.10, 0.15, 0.18, 0.20])

multiply_price_tax = new_price * tax_rates

print(multiply_price_tax)

# Each row is one order, each column is a tax rate. 
# 1 price (38.08) to all the tax

Prices before [ 38.08    100.       73.47     69.3105   16.45     16.44     15.57225
  99.7625   60.51     81.765  ]
[[ 1.904      3.808      5.712      6.8544     7.616    ]
 [ 5.        10.        15.        18.        20.       ]
 [ 3.6735     7.347     11.0205    13.2246    14.694    ]
 [ 3.465525   6.93105   10.396575  12.47589   13.8621   ]
 [ 0.8225     1.645      2.4675     2.961      3.29     ]
 [ 0.822      1.644      2.466      2.9592     3.288    ]
 [ 0.7786125  1.557225   2.3358375  2.803005   3.11445  ]
 [ 4.988125   9.97625   14.964375  17.95725   19.9525   ]
 [ 3.0255     6.051      9.0765    10.8918    12.102    ]
 [ 4.08825    8.1765    12.26475   14.7177    16.353    ]]


In [ ]:
# Split the 10-order dataset into 2 equal chunks of 5 orders each.

result = np.array_split(Order_ID, 2)
result

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [164]:
stack_array

array([[3.808e+01, 9.512e+01, 7.347e+01, 6.027e+01, 1.645e+01, 1.644e+01,
        6.750e+00, 8.675e+01, 6.051e+01, 7.110e+01],
       [2.000e+00, 1.200e+01, 6.000e+00, 2.000e+00, 1.000e+00, 1.200e+01,
        1.200e+01, 1.700e+01, 1.000e+01, 1.600e+01],
       [1.200e-01, 5.000e-02, 3.100e-01, 1.900e-01, 4.900e-01, 2.300e-01,
        4.300e-01, 3.400e-01, 2.300e-01, 1.000e-02],
       [4.770e+00, 3.250e+00, 2.540e+00, 1.060e+00, 1.920e+00, 1.960e+00,
        3.730e+00, 3.440e+00, 4.330e+00, 1.690e+00],
       [1.000e+00, 4.000e+00, 2.000e+00, 8.000e+00, 4.000e+00, 2.000e+00,
        6.000e+00, 6.000e+00, 4.000e+00, 6.000e+00],
       [4.000e+00, 1.000e+00, 1.000e+00, 3.000e+00, 1.000e+00, 1.000e+00,
        3.000e+00, 3.000e+00, 0.000e+00, 4.000e+00],
       [1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        1.000e+00, 0.000e+00, 1.000e+00, 1.000e+00]])

In [168]:
# Stack two separate 5-order arrays (first half and second half of orders) back into one 10-order array.

first_half = Order_ID[:5]
second_half = Order_ID[5:]

print(first_half)
print(second_half)

concat_arrays = np.concatenate((first_half, second_half))
concat_arrays

[1 2 3 4 5]
[ 6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Linear algebra

In [ ]:
# Build a (4×4) category-rating co-occurrence matrix: entry [i,j] = count of orders in category i with rating j.
# print("category", category)
# print("Rtaing",rating)

# matrix = np.zeros((5,4))
# np.add.at(matrix, [category, rating-1], 1)
# matrix

# doubtful

In [ ]:
# Compute the dot product of the price and quantity arrays (treating them as vectors).

print("Price",price)
print("quantity",quantity)
dot_product = np.dot(price,quantity)
dot_product

#Multiply each item by its value, then add everything up

Price [ 38.08    100.       73.47     69.3105   16.45     16.44     15.57225
  99.7625   60.51     81.765  ]
quantity [ 2 12  6  2  1 12 12 17 10 16]


np.float64(5865.5005)

In [ ]:
# Normalize the revenue column to unit norm (L2 normalization).

print("Revenue", revenue)
norm_revenue = np.linalg.norm(revenue)
norm_revenue   # this is scalar value

# Norm is use to treat all the elements same

Revenue [  67.0208  100.      304.1658   97.6374    8.3895  151.9056   46.17
  973.335   465.927  1126.224 ]


np.float64(1604.57737022951)

In [185]:
# Given a 3×3 feature matrix built from [mean_price, mean_qty, mean_discount] per first 3 categories, compute its determinant and check if it's invertible.

# filter orders with category 0
# mean_price_cat0 = price[category==0].mean()
# mean_quantity_cat0 = quantity[category==0].mean()
# mean_discount_cat0 = discount[category==0].mean()

# # category 1
# mean_price_cat1 = price[category==1].mean()
# mean_quantity_cat1 = quantity[category==1].mean()
# mean_discount_cat1 = discount[category==1].mean()

# # category 2
# mean_price_cat2 = price[category==2].mean()
# mean_quantity_cat2 = quantity[category==2].mean()
# mean_discount_cat2 = discount[category==2].mean()

# needs more understanding